//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountReceivableAdjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountReceivableAdjustment()
        {
            this.SalesCustomerLedgers = new HashSet<SalesCustomerLedger>();
            this.tblGLTranHeaders = new HashSet<tblGLTranHeader>();
            this.AccountReceivableAdjustmentsDetails = new HashSet<AccountReceivableAdjustmentsDetail>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AccountsReceivableAdjustmentsTypeId { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> CollectionId { get; set; }
        public Nullable<int> SalesId { get; set; }
        public string Descrpition { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> TotalInventoryAmount { get; set; }
        public string AdditionalDescription { get; set; }
        public Nullable<decimal> SOPAmount { get; set; }
        public Nullable<decimal> COMMAmount { get; set; }
        public Nullable<decimal> CFAmount { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual AccountsReceivableAdjustmentsType AccountsReceivableAdjustmentsType { get; set; }
        public virtual Collection Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesCustomerLedger> SalesCustomerLedgers { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGLTranHeader> tblGLTranHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountReceivableAdjustmentsDetail> AccountReceivableAdjustmentsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
