//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPayableAdjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountPayableAdjustment()
        {
            this.PurchaseSupplierLedgers = new HashSet<PurchaseSupplierLedger>();
            this.tblGLTranHeaders = new HashSet<tblGLTranHeader>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AccountsPayableAdjustmentTypeId { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> SupplierId { get; set; }
    
        public virtual AccountsPayableAdjustmentsType AccountsPayableAdjustmentsType { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Purchase Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseSupplierLedger> PurchaseSupplierLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGLTranHeader> tblGLTranHeaders { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
