//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bank()
        {
            this.Suppliers = new HashSet<Supplier>();
            this.Collections = new HashSet<Collection>();
        }
    
        public int Id { get; set; }
        public string strName { get; set; }
        public string strAccountNo { get; set; }
        public string strAccountName { get; set; }
        public string strBranch { get; set; }
        public Nullable<decimal> curStartingDebit { get; set; }
        public Nullable<decimal> curDebit { get; set; }
        public Nullable<decimal> curCredit { get; set; }
        public Nullable<decimal> curBalance { get; set; }
        public Nullable<int> intIDCurrency { get; set; }
    
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collections { get; set; }
    }
}
