//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collection()
        {
            this.tblGLTranHeaders = new HashSet<tblGLTranHeader>();
            this.AccountReceivableAdjustments = new HashSet<AccountReceivableAdjustment>();
            this.SalesCustomerLedgers = new HashSet<SalesCustomerLedger>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TRANo { get; set; }
        public Nullable<int> SalesId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> IsCash { get; set; }
        public Nullable<int> BankId { get; set; }
        public string CheckDetail { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> RunningBalance { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Sale Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGLTranHeader> tblGLTranHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountReceivableAdjustment> AccountReceivableAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesCustomerLedger> SalesCustomerLedgers { get; set; }
    }
}
