//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.SalesCustomerLedgers = new HashSet<SalesCustomerLedger>();
            this.Sales = new HashSet<Sale>();
            this.AccountReceivableAdjustments = new HashSet<AccountReceivableAdjustment>();
        }
    
        public int Id { get; set; }
        public string strName { get; set; }
        public Nullable<decimal> curStartingDebit { get; set; }
        public Nullable<decimal> curDebit { get; set; }
        public Nullable<decimal> curCredit { get; set; }
        public Nullable<decimal> curCreditLimit { get; set; }
        public Nullable<int> intTerms { get; set; }
        public Nullable<int> intIDPriceType { get; set; }
        public string strAddress { get; set; }
        public string strContact { get; set; }
    
        public virtual PriceType PriceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesCustomerLedger> SalesCustomerLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountReceivableAdjustment> AccountReceivableAdjustments { get; set; }
    }
}
