//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GeneralLedgerContext : DbContext
    {
        public GeneralLedgerContext()
            : base("name=GeneralLedgerContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<InventoryLog> InventoryLogs { get; set; }
        public virtual DbSet<InventoryLogOperationType> InventoryLogOperationTypes { get; set; }
        public virtual DbSet<InventoryQuantityTotal> InventoryQuantityTotals { get; set; }
        public virtual DbSet<InventoryStock> InventoryStocks { get; set; }
        public virtual DbSet<InventoryStockDetail> InventoryStockDetails { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<PriceType> PriceTypes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductBrand> ProductBrands { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductCharacteristic> ProductCharacteristics { get; set; }
        public virtual DbSet<ProductColor> ProductColors { get; set; }
        public virtual DbSet<ProductDetail> ProductDetails { get; set; }
        public virtual DbSet<ProductSize> ProductSizes { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<ProductUnit> ProductUnits { get; set; }
        public virtual DbSet<PuchaseOrderReceivingStatu> PuchaseOrderReceivingStatus { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PurchaseOrderCustomerLedger> PurchaseOrderCustomerLedgers { get; set; }
        public virtual DbSet<PurchaseOrderCustomerLedgerDetail> PurchaseOrderCustomerLedgerDetails { get; set; }
        public virtual DbSet<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual DbSet<PurchaseOrderDetailInventoryLedger> PurchaseOrderDetailInventoryLedgers { get; set; }
        public virtual DbSet<PurchaseOrderInventoryLedger> PurchaseOrderInventoryLedgers { get; set; }
        public virtual DbSet<PurchaseOrderPayment> PurchaseOrderPayments { get; set; }
        public virtual DbSet<PurchaseOrderPaymentStatu> PurchaseOrderPaymentStatus { get; set; }
        public virtual DbSet<PurchaseOrderProductDetailHistory> PurchaseOrderProductDetailHistories { get; set; }
        public virtual DbSet<PurchaseOrderProductTransactionType> PurchaseOrderProductTransactionTypes { get; set; }
        public virtual DbSet<PurchaseOrderReceiving> PurchaseOrderReceivings { get; set; }
        public virtual DbSet<PurchaseOrderReceivingDetail> PurchaseOrderReceivingDetails { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblGLTranDetail> tblGLTranDetails { get; set; }
        public virtual DbSet<tblLocation> tblLocations { get; set; }
        public virtual DbSet<tblMasCOA> tblMasCOAs { get; set; }
        public virtual DbSet<tblMasCOAGroup> tblMasCOAGroups { get; set; }
        public virtual DbSet<tblMasCOASub> tblMasCOASubs { get; set; }
        public virtual DbSet<tblTBBatchDtl> tblTBBatchDtls { get; set; }
        public virtual DbSet<tblTBBatchHdr> tblTBBatchHdrs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<tblJournalEntry> tblJournalEntries { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<tblGLBookType> tblGLBookTypes { get; set; }
        public virtual DbSet<tblGLTranHeader> tblGLTranHeaders { get; set; }
        public virtual DbSet<Collection> Collections { get; set; }
        public virtual DbSet<SalesCustomerLedgerTransactionType> SalesCustomerLedgerTransactionTypes { get; set; }
        public virtual DbSet<SalesCustomerLedger> SalesCustomerLedgers { get; set; }
    
        public virtual ObjectResult<spGetSalesCustomerLedger_Result> spGetSalesCustomerLedger(Nullable<int> salesID)
        {
            var salesIDParameter = salesID.HasValue ?
                new ObjectParameter("SalesID", salesID) :
                new ObjectParameter("SalesID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSalesCustomerLedger_Result>("spGetSalesCustomerLedger", salesIDParameter);
        }
    }
}
