//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryLog
    {
        public int Id { get; set; }
        public Nullable<int> intProductDetailId { get; set; }
        public Nullable<int> intQuantity { get; set; }
        public Nullable<int> intInventoryLogOperationType { get; set; }
        public Nullable<System.DateTime> datDateInserted { get; set; }
        public Nullable<int> intQuantityBefore { get; set; }
        public Nullable<int> intQuantityAfter { get; set; }
        public Nullable<int> intIDReference { get; set; }
    }
}
