//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryStock
    {
        public int Id { get; set; }
        public Nullable<int> intIDProduct { get; set; }
        public Nullable<int> intIDProductDetail { get; set; }
        public Nullable<int> intStockCount { get; set; }
        public Nullable<int> blnIsActive { get; set; }
        public Nullable<System.DateTime> datLastModified { get; set; }
    }
}
