//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryQuantityTotal
    {
        public int Id { get; set; }
        public Nullable<int> intProductId { get; set; }
        public Nullable<int> intProductDetailId { get; set; }
        public Nullable<int> intQuantityOnHand { get; set; }
        public Nullable<int> intQuantityOnSold { get; set; }
        public Nullable<int> intQuantityOnOrder { get; set; }
    }
}
