//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryStockDetail
    {
        public int Id { get; set; }
        public Nullable<int> intIDInventoryStock { get; set; }
        public Nullable<int> intIDReference { get; set; }
        public Nullable<int> intQuantity { get; set; }
        public Nullable<int> datTransactionDate { get; set; }
        public Nullable<int> intIDInventoryStockOperationType { get; set; }
    }
}
