//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAY2025
    {
        public string Product_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string Price_Type { get; set; }
        public Nullable<double> TOTAL_NUMBER_OF_PCS_ { get; set; }
        public string Product_Unit { get; set; }
        public Nullable<double> Unit_Price { get; set; }
        public string Product_Categories { get; set; }
        public string Product_Types { get; set; }
        public string Product_Brand { get; set; }
        public string Product_Color { get; set; }
        public string Product_Size { get; set; }
        public string Location { get; set; }
        public string PR { get; set; }
        public string Origin { get; set; }
        public string Pattern { get; set; }
        public string MF_LM { get; set; }
        public string PCD { get; set; }
        public string Offset_CenterBore { get; set; }
        public int MAY2025ID { get; set; }
    }
}
