//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.tblGLTranHeaders = new HashSet<tblGLTranHeader>();
            this.PurchaseSupplierLedgers = new HashSet<PurchaseSupplierLedger>();
            this.AccountPayableAdjustments = new HashSet<AccountPayableAdjustment>();
        }
    
        public int Id { get; set; }
        public string PaymentCV { get; set; }
        public string PaymentSIDR { get; set; }
        public Nullable<System.DateTime> PaymentTransactionDate { get; set; }
        public Nullable<decimal> PaymentTotal { get; set; }
        public Nullable<int> PaymentBankId { get; set; }
        public Nullable<bool> PaymentIsCash { get; set; }
        public string PaymentCheckDetail { get; set; }
        public string PaymentDescription { get; set; }
        public Nullable<int> PurchaseId { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGLTranHeader> tblGLTranHeaders { get; set; }
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseSupplierLedger> PurchaseSupplierLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPayableAdjustment> AccountPayableAdjustments { get; set; }
    }
}
