//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int Id { get; set; }
        public Nullable<int> intIDProduct { get; set; }
        public Nullable<int> intIDProductColor { get; set; }
        public Nullable<int> intIDProductSize { get; set; }
        public Nullable<int> intMininum { get; set; }
        public Nullable<int> intLength { get; set; }
        public Nullable<int> intWidth { get; set; }
        public Nullable<int> intHeight { get; set; }
        public Nullable<decimal> curCargoCost { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductColor ProductColor { get; set; }
        public virtual ProductDetail ProductDetail1 { get; set; }
        public virtual ProductDetail ProductDetail2 { get; set; }
        public virtual ProductSize ProductSize { get; set; }
    }
}
