//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string strProductName { get; set; }
        public string strDescription { get; set; }
        public Nullable<int> intIDProductCategory { get; set; }
        public Nullable<int> intIDProductType { get; set; }
        public Nullable<int> intIDProductBrands { get; set; }
        public Nullable<int> intPerPiecePerBox { get; set; }
        public Nullable<int> intIDLocation { get; set; }
        public Nullable<int> intTotal { get; set; }
        public Nullable<int> intIDPriceType { get; set; }
        public Nullable<int> intIDProductCharacteristic { get; set; }
        public Nullable<int> intIDSize { get; set; }
        public Nullable<int> intIDColor { get; set; }
        public string strCode { get; set; }
        public string strPR { get; set; }
        public string strPCD { get; set; }
        public string strMFLM { get; set; }
        public string strPattern { get; set; }
        public string strOrigin { get; set; }
        public string strOffsetCenterBore { get; set; }
        public Nullable<int> intIDProductUnit { get; set; }
        public Nullable<decimal> curUnitPrice { get; set; }
        public Nullable<int> intRemainingCount { get; set; }
    
        public virtual PriceType PriceType { get; set; }
        public virtual ProductBrand ProductBrand { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductCharacteristic ProductCharacteristic { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual ProductColor ProductColor { get; set; }
        public virtual ProductSize ProductSize { get; set; }
        public virtual ProductUnit ProductUnit { get; set; }
    }
}
