//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductDetails = new HashSet<ProductDetail>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        }
    
        public int Id { get; set; }
        public string strProductName { get; set; }
        public string strDescription { get; set; }
        public Nullable<int> intIDProductCategory { get; set; }
        public Nullable<int> intIDProductType { get; set; }
        public Nullable<int> intIDProductBrands { get; set; }
        public Nullable<int> intDefaultMinimum { get; set; }
        public Nullable<int> intPerPiecePerBox { get; set; }
        public Nullable<int> intIDLocation { get; set; }
        public Nullable<int> intDefaultLength { get; set; }
        public Nullable<int> intDefaultWidth { get; set; }
        public Nullable<int> intDefaultHeight { get; set; }
        public Nullable<int> intDefaultCargoCost { get; set; }
        public Nullable<int> intTotal { get; set; }
        public Nullable<decimal> curDefaultCost { get; set; }
        public Nullable<int> intIDPriceType { get; set; }
        public Nullable<decimal> curDefaultRetail { get; set; }
        public Nullable<decimal> curDefaultWholesale { get; set; }
        public Nullable<decimal> curDefaultMarkup { get; set; }
        public Nullable<int> intIDProductCharacteristic { get; set; }
    
        public virtual PriceType PriceType { get; set; }
        public virtual ProductBrand ProductBrand { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductCharacteristic ProductCharacteristic { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
    }
}
