//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderReceiving
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderReceiving()
        {
            this.PurchaseOrderReceivingDetails = new HashSet<PurchaseOrderReceivingDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> intIDPurchaseOrder { get; set; }
        public Nullable<System.DateTime> datDateReceived { get; set; }
        public Nullable<int> intIDLocation { get; set; }
        public string strAddress { get; set; }
        public string strMemo { get; set; }
        public Nullable<System.DateTime> datDateInserted { get; set; }
        public Nullable<bool> blnReceivedOnPO { get; set; }
        public Nullable<int> curTotalQty { get; set; }
        public Nullable<int> curTotalReceived { get; set; }
        public Nullable<int> curTotalRemaining { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderReceivingDetail> PurchaseOrderReceivingDetails { get; set; }
    }
}
