//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.Payments = new HashSet<Payment>();
            this.PurchaseSupplierLedgers = new HashSet<PurchaseSupplierLedger>();
            this.AccountPayableAdjustments = new HashSet<AccountPayableAdjustment>();
            this.Stocks = new HashSet<Stock>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.tblGLTranHeaders = new HashSet<tblGLTranHeader>();
        }
    
        public int Id { get; set; }
        public string PONo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> intIDSupplier { get; set; }
        public string SIDR { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Description { get; set; }
        public Nullable<int> Terms { get; set; }
        public string TRANo { get; set; }
        public Nullable<bool> IsFullyPaid { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<bool> IsPurchaseReturn { get; set; }
        public string AdditionalDescription { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseSupplierLedger> PurchaseSupplierLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPayableAdjustment> AccountPayableAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGLTranHeader> tblGLTranHeaders { get; set; }
    }
}
