//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.PurchaseOrderCustomerLedgers = new HashSet<PurchaseOrderCustomerLedger>();
            this.PurchaseOrderInventoryLedgers = new HashSet<PurchaseOrderInventoryLedger>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.PurchaseOrderPayments = new HashSet<PurchaseOrderPayment>();
        }
    
        public int Id { get; set; }
        public string strPONumber { get; set; }
        public Nullable<int> intIDSupplier { get; set; }
        public Nullable<int> intIDLocation { get; set; }
        public Nullable<System.DateTime> datDatePurchased { get; set; }
        public Nullable<decimal> curTotalQty { get; set; }
        public Nullable<decimal> curSubTotal { get; set; }
        public Nullable<decimal> curDiscount { get; set; }
        public Nullable<decimal> curDiscountPercentage { get; set; }
        public Nullable<decimal> curGrandTotal { get; set; }
        public Nullable<decimal> curTotalPaid { get; set; }
        public Nullable<decimal> curTotalReceived { get; set; }
        public Nullable<decimal> curTotalRemaining { get; set; }
        public Nullable<bool> blnHasPayment { get; set; }
        public Nullable<decimal> curAmountPaid { get; set; }
        public Nullable<decimal> curChange { get; set; }
        public Nullable<bool> blnApproved { get; set; }
        public Nullable<int> intIDApprover { get; set; }
        public Nullable<System.DateTime> datDateApproved { get; set; }
        public Nullable<bool> blnAddBalanceToSupplier { get; set; }
        public Nullable<System.DateTime> datDateInserted { get; set; }
        public Nullable<int> intIDCreatedBy { get; set; }
        public Nullable<int> intIDReceivingStatus { get; set; }
    
        public virtual PuchaseOrderReceivingStatu PuchaseOrderReceivingStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderCustomerLedger> PurchaseOrderCustomerLedgers { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderInventoryLedger> PurchaseOrderInventoryLedgers { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderPayment> PurchaseOrderPayments { get; set; }
    }
}
