//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderCustomerLedgerDetail
    {
        public int ID { get; set; }
        public Nullable<int> intIDPurchaseOrderCustomerLedger { get; set; }
        public Nullable<int> intIDPaymentType { get; set; }
        public string strReference { get; set; }
        public Nullable<System.DateTime> datDate { get; set; }
        public Nullable<decimal> curAmountPaid { get; set; }
        public Nullable<decimal> curChange { get; set; }
    
        public virtual PurchaseOrderCustomerLedger PurchaseOrderCustomerLedger { get; set; }
    }
}
