//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderCustomerLedger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderCustomerLedger()
        {
            this.PurchaseOrderCustomerLedgerDetails = new HashSet<PurchaseOrderCustomerLedgerDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> intIDPurchaseOrder { get; set; }
        public Nullable<decimal> curSubTotal { get; set; }
        public Nullable<decimal> curDiscount { get; set; }
        public Nullable<decimal> curGrandTotal { get; set; }
        public Nullable<decimal> curTotalPaidPendingPayments { get; set; }
        public Nullable<decimal> curTotalDiscountsPendingDiscounts { get; set; }
        public Nullable<decimal> curTotalChangePendingChange { get; set; }
        public Nullable<decimal> curTotalBalance { get; set; }
        public Nullable<System.DateTime> datDateInserted { get; set; }
        public Nullable<bool> bitIsActive { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderCustomerLedgerDetail> PurchaseOrderCustomerLedgerDetails { get; set; }
    }
}
