//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderPayment
    {
        public int Id { get; set; }
        public Nullable<int> intIDPurchaseOrder { get; set; }
        public Nullable<System.DateTime> datPaidOn { get; set; }
        public string datPaidBy { get; set; }
        public Nullable<decimal> curTotalAmount { get; set; }
        public Nullable<decimal> curDiscount { get; set; }
        public Nullable<decimal> curGrandTotal { get; set; }
        public Nullable<decimal> curAmountPaid { get; set; }
        public Nullable<int> intIDPurchaseOrderPaymentStatus { get; set; }
        public string strBankAccounts { get; set; }
        public Nullable<System.DateTime> curDatCheckDate { get; set; }
        public string strCheckNo { get; set; }
        public Nullable<System.DateTime> datApprovedOn { get; set; }
        public string datApprovedBy { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
