//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetailInventoryLedger
    {
        public int Id { get; set; }
        public Nullable<int> intIDPurchaseOrderInventoryLedger { get; set; }
        public Nullable<int> intIDPurchaseOrder { get; set; }
        public Nullable<int> intIDPurchaseOrderDetail { get; set; }
        public Nullable<int> curStock { get; set; }
        public Nullable<int> curActStock { get; set; }
        public Nullable<int> intQuantity { get; set; }
        public Nullable<int> intQuantityReceived { get; set; }
        public Nullable<int> intQuantityRemaining { get; set; }
        public Nullable<int> intIDReceivingStatus { get; set; }
    
        public virtual PuchaseOrderReceivingStatu PuchaseOrderReceivingStatu { get; set; }
        public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }
        public virtual PurchaseOrderInventoryLedger PurchaseOrderInventoryLedger { get; set; }
    }
}
