//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderReceivingDetail
    {
        public int Id { get; set; }
        public Nullable<int> intIDPurchaseOrderReceiving { get; set; }
        public Nullable<int> intIDPurchaseOrderDetail { get; set; }
        public Nullable<int> intQuantity { get; set; }
        public Nullable<int> intQuantityReceived { get; set; }
        public Nullable<int> intQuantityRemaining { get; set; }
        public Nullable<int> intAddedQuantityReceived { get; set; }
        public Nullable<bool> blnIsReceived { get; set; }
        public Nullable<System.DateTime> datDateInserted { get; set; }
    
        public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }
        public virtual PurchaseOrderReceiving PurchaseOrderReceiving { get; set; }
    }
}
