//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderInventoryLedger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderInventoryLedger()
        {
            this.PurchaseOrderDetailInventoryLedgers = new HashSet<PurchaseOrderDetailInventoryLedger>();
        }
    
        public int Id { get; set; }
        public Nullable<int> intIDPurchaseOrder { get; set; }
        public Nullable<System.DateTime> datDateInserted { get; set; }
        public Nullable<int> curTotalQty { get; set; }
        public Nullable<int> curTotalReceived { get; set; }
        public Nullable<int> curTotalRemaining { get; set; }
        public Nullable<int> intIDReceivingStatus { get; set; }
    
        public virtual PuchaseOrderReceivingStatu PuchaseOrderReceivingStatu { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetailInventoryLedger> PurchaseOrderDetailInventoryLedgers { get; set; }
    }
}
