//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderDetail()
        {
            this.PurchaseOrderDetailInventoryLedgers = new HashSet<PurchaseOrderDetailInventoryLedger>();
            this.PurchaseOrderProductDetailHistories = new HashSet<PurchaseOrderProductDetailHistory>();
            this.PurchaseOrderReceivingDetails = new HashSet<PurchaseOrderReceivingDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> intIDPurchaseOrder { get; set; }
        public Nullable<int> intIDProduct { get; set; }
        public Nullable<int> intIDProductDetail { get; set; }
        public Nullable<int> curStock { get; set; }
        public Nullable<int> curActStock { get; set; }
        public Nullable<int> intQuantity { get; set; }
        public Nullable<int> intQuantityReceived { get; set; }
        public Nullable<int> intQuantityRemaining { get; set; }
        public Nullable<decimal> curCost { get; set; }
        public Nullable<decimal> curSubTotal { get; set; }
        public Nullable<int> intIDReceivingStatus { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual PuchaseOrderReceivingStatu PuchaseOrderReceivingStatu { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetailInventoryLedger> PurchaseOrderDetailInventoryLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderProductDetailHistory> PurchaseOrderProductDetailHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderReceivingDetail> PurchaseOrderReceivingDetails { get; set; }
    }
}
