//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderProductDetailHistory
    {
        public int Id { get; set; }
        public Nullable<int> intIDPurchaseOrderDetail { get; set; }
        public Nullable<int> intIDPurchaseOrderProductTransactionType { get; set; }
        public string strTransactionType { get; set; }
        public Nullable<int> intQuantity { get; set; }
        public Nullable<int> intTotalReceived { get; set; }
        public Nullable<int> intTotalReturn { get; set; }
        public Nullable<int> intTotalRemaining { get; set; }
        public Nullable<System.DateTime> datDateInserted { get; set; }
    
        public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }
        public virtual PurchaseOrderProductTransactionType PurchaseOrderProductTransactionType { get; set; }
    }
}
