//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesCustomerLedger
    {
        public int Id { get; set; }
        public Nullable<int> intIdSalesCustomerLedgerTransctionType { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> intIdSales { get; set; }
        public Nullable<int> intIdCollection { get; set; }
        public Nullable<System.DateTime> DateInserted { get; set; }
    
        public virtual Collection Collection { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual SalesCustomerLedgerTransactionType SalesCustomerLedgerTransactionType { get; set; }
    }
}
