//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.AccountReceivableAdjustments = new HashSet<AccountReceivableAdjustment>();
            this.Collections = new HashSet<Collection>();
            this.SalesCustomerLedgers = new HashSet<SalesCustomerLedger>();
            this.tblGLTranHeaders = new HashSet<tblGLTranHeader>();
        }
    
        public int Id { get; set; }
        public string TRANo { get; set; }
        public string PONo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> intIdCustomer { get; set; }
        public Nullable<int> intIdAgent { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> Terms { get; set; }
        public Nullable<bool> IsFullyPaid { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<decimal> SOPAmount { get; set; }
        public Nullable<decimal> COMMAmount { get; set; }
        public Nullable<decimal> CFAmount { get; set; }
        public Nullable<bool> IsSalesReturn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountReceivableAdjustment> AccountReceivableAdjustments { get; set; }
        public virtual Agent Agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collections { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesCustomerLedger> SalesCustomerLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGLTranHeader> tblGLTranHeaders { get; set; }
    }
}
