//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public string TRANo { get; set; }
        public string PONo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> intIdCustomer { get; set; }
        public Nullable<int> intIdAgent { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Agent Agent { get; set; }
    }
}
