//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> StockTransactionTypeID { get; set; }
        public Nullable<int> QuantityIn { get; set; }
        public Nullable<int> QuantityOut { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<int> SalesID { get; set; }
        public Nullable<int> AccountsPayablePurchaseReturnID { get; set; }
        public Nullable<int> AccountsReceivableSaleReturnID { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual StockTransactionType StockTransactionType { get; set; }
        public virtual Product Product { get; set; }
        public virtual AccountPayableAdjustment AccountPayableAdjustment { get; set; }
        public virtual AccountReceivableAdjustment AccountReceivableAdjustment { get; set; }
    }
}
