//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Purchases = new HashSet<Purchase>();
            this.PurchaseSupplierLedgers = new HashSet<PurchaseSupplierLedger>();
            this.AccountPayableAdjustments = new HashSet<AccountPayableAdjustment>();
        }
    
        public int Id { get; set; }
        public string strName { get; set; }
        public Nullable<int> intIDCurrency { get; set; }
        public Nullable<decimal> curStartingDebit { get; set; }
        public Nullable<decimal> curDebit { get; set; }
        public Nullable<decimal> curCredit { get; set; }
        public Nullable<decimal> curBalance { get; set; }
        public string strAddress { get; set; }
        public string strContacts { get; set; }
        public Nullable<int> intIDBank { get; set; }
    
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseSupplierLedger> PurchaseSupplierLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountPayableAdjustment> AccountPayableAdjustments { get; set; }
    }
}
