//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGLTranDetail
    {
        public int ID { get; set; }
        public int intIDGLTranHeader { get; set; }
        public int intIDMasCoa { get; set; }
        public int intIDMasCoaSub { get; set; }
        public Nullable<decimal> curDebit { get; set; }
        public Nullable<decimal> curCredit { get; set; }
    
        public virtual tblGLTranHeader tblGLTranHeader { get; set; }
        public virtual tblMasCOA tblMasCOA { get; set; }
    }
}
