//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGLTranHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGLTranHeader()
        {
            this.tblGLTranDetails = new HashSet<tblGLTranDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> intIDGLBookType { get; set; }
        public Nullable<System.DateTime> datBatchDate { get; set; }
        public Nullable<int> intIDReference { get; set; }
        public string strTransactionCode { get; set; }
        public Nullable<decimal> curCreditAmount { get; set; }
        public Nullable<decimal> curDebitAmount { get; set; }
        public Nullable<System.DateTime> datInsertedDate { get; set; }
        public string strDescription { get; set; }
        public Nullable<int> intIdSales { get; set; }
        public Nullable<int> intIdCollection { get; set; }
        public Nullable<int> intIdPurchase { get; set; }
        public Nullable<bool> blnUseDefaultEntry { get; set; }
        public Nullable<int> intIdAccountReceivableAdjustment { get; set; }
        public Nullable<int> intIdPayment { get; set; }
        public Nullable<int> intIdAccountPayableAdjustment { get; set; }
    
        public virtual tblGLBookType tblGLBookType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGLTranDetail> tblGLTranDetails { get; set; }
        public virtual tblJournalEntry tblJournalEntry { get; set; }
        public virtual Collection Collection { get; set; }
        public virtual Purchase Purchase { get; set; }
        public virtual tblGLTranHeader tblGLTranHeader1 { get; set; }
        public virtual tblGLTranHeader tblGLTranHeader2 { get; set; }
        public virtual AccountReceivableAdjustment AccountReceivableAdjustment { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual AccountPayableAdjustment AccountPayableAdjustment { get; set; }
    }
}
