//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasCOASub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMasCOASub()
        {
            this.tblGLTranDetails = new HashSet<tblGLTranDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> intIDMasCOA { get; set; }
        public string strCode { get; set; }
        public string strName { get; set; }
        public Nullable<int> intIDBank { get; set; }
    
        public virtual tblMasCOA tblMasCOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGLTranDetail> tblGLTranDetails { get; set; }
        public virtual Bank Bank { get; set; }
    }
}
