//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMasCOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMasCOA()
        {
            this.tblMasCOASubs = new HashSet<tblMasCOASub>();
            this.tblGLTranDetails = new HashSet<tblGLTranDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> intIDMasCOAGroup { get; set; }
        public string strCode { get; set; }
        public string strName { get; set; }
        public string strAcctSide { get; set; }
        public string strAcctType { get; set; }
        public Nullable<int> intIncomeStatementOrderby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMasCOASub> tblMasCOASubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGLTranDetail> tblGLTranDetails { get; set; }
    }
}
