//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTBBatchHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTBBatchHdr()
        {
            this.tblTBBatchDtls = new HashSet<tblTBBatchDtl>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> datBatchDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> bitIsLock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTBBatchDtl> tblTBBatchDtls { get; set; }
    }
}
