//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralLedger.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTBBatchDtl
    {
        public int ID { get; set; }
        public int intIDTBBatchHdr { get; set; }
        public Nullable<int> COA { get; set; }
        public string COADesc { get; set; }
        public Nullable<int> COASub { get; set; }
        public string COASubDesc { get; set; }
        public Nullable<decimal> curBegBal { get; set; }
        public Nullable<decimal> curDebit { get; set; }
        public Nullable<decimal> curCredit { get; set; }
        public Nullable<decimal> curEndBal { get; set; }
        public Nullable<decimal> curAdjustedDebit { get; set; }
        public Nullable<decimal> curAdjustedCredit { get; set; }
        public Nullable<decimal> curEndBalAdjusted { get; set; }
    
        public virtual tblTBBatchHdr tblTBBatchHdr { get; set; }
    }
}
